name = "Hugo ReFresh"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/PippoRJ/hugo-refresh/master/LICENSE"
description = "A multi-page, clean and responsive theme. Multilingual supported."
homepage = "https://github.com/PippoRJ/hugo-refresh"
tags = ["responsive", "blog", "light", "clean", "personal", "multilingual", "syntax-highlighting"]
features = ["blog", "responsive", "simple", "404", "mathjax"]
min_version = "0.45"

[author]
  name = "Roberto Jordaney"
  homepage = "https://github.com/PippoRJ"